/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EstadoCad.java
 *
 * Created on 25/07/2011, 20:39:45
 */
package visao;

import java.awt.Frame;

/**
 *
 * @author Jaime
 */
public class TelaPrincipal extends javax.swing.JDialog {

    

    /** Creates new form EstadoCad */
    public TelaPrincipal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        
    }

    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        Cadastro = new javax.swing.JMenu();
        ClienteCad = new javax.swing.JMenuItem();
        CidadeCad = new javax.swing.JMenuItem();
        EstadoCad = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Cadastro.setText("Cadastros");
        Cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroActionPerformed(evt);
            }
        });

        ClienteCad.setText("Clientes");
        ClienteCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteCadActionPerformed(evt);
            }
        });
        Cadastro.add(ClienteCad);

        CidadeCad.setText("Cidade");
        CidadeCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CidadeCadActionPerformed(evt);
            }
        });
        Cadastro.add(CidadeCad);

        EstadoCad.setText("Estado");
        EstadoCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadoCadActionPerformed(evt);
            }
        });
        Cadastro.add(EstadoCad);

        jMenuBar1.add(Cadastro);

        jMenu2.setText("Movimentos");

        jMenuItem4.setText("Vendas");
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Relatorios");
        jMenuBar1.add(jMenu1);

        jMenu3.setText("Ações");

        jMenuItem5.setText("Sair");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 671, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroActionPerformed

        
        // TODO add your handling code here:
    }//GEN-LAST:event_CadastroActionPerformed

    private void EstadoCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadoCadActionPerformed

        Frame EstadoCad = null; //ClienteCad é o nome do formulario
        EstadoCad f = new EstadoCad(EstadoCad, rootPaneCheckingEnabled);
        f.setVisible(rootPaneCheckingEnabled);
        // TODO add your handling code here:
    }//GEN-LAST:event_EstadoCadActionPerformed

    private void ClienteCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteCadActionPerformed

        Frame ClienteCad = null; //ClienteCad é o nome do formulario
        ClienteCad f = new ClienteCad(ClienteCad, rootPaneCheckingEnabled);
        f.setVisible(rootPaneCheckingEnabled);
        // TODO add your handling code here:
    }//GEN-LAST:event_ClienteCadActionPerformed

    private void CidadeCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CidadeCadActionPerformed
       
        Frame CidadeCad = null; //ClienteCad é o nome do formulario
        CidadeCad f = new CidadeCad(CidadeCad, rootPaneCheckingEnabled);
        f.setVisible(rootPaneCheckingEnabled);
        // TODO add your handling code here:
    }//GEN-LAST:event_CidadeCadActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed

        System.exit(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                TelaPrincipal dialog = new TelaPrincipal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Cadastro;
    private javax.swing.JMenuItem CidadeCad;
    private javax.swing.JMenuItem ClienteCad;
    private javax.swing.JMenuItem EstadoCad;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    // End of variables declaration//GEN-END:variables
}
